---
services:
  php:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app:z
      - ./frankenphp/Caddyfile:/etc/frankenphp/Caddyfile:ro,z
      - ./frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro,z
      #- /app/vendor
    environment:
      FRANKENPHP_WORKER_CONFIG: watch
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      APP_ENV: "${APP_ENV:-dev}"
    extra_hosts:
      - host.docker.internal:host-gateway
    tty: true

  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3306"
  ###< doctrine/doctrine-bundle ###
